import type { ActivationSnapshot, ForwardingGuide } from "@/lib/types/activation";

export function forwardingGuide(): ForwardingGuide {
  return {
    version: "fr-carrier-guidance-v1",
    carrier: "orange",
    number_type: "fixed",
    presvo_number: "+33187654321",
    warning: "Use conditional forwarding only.",
    steps: [
      {
        condition: "unanswered",
        title: "When unanswered",
        instructions: ["Dial the code and call it."],
        dial_code: "*61*0187654321#",
        disable_code: "##61#",
        source_url: "https://assistance.orange.fr/conditional-forwarding",
      },
      {
        condition: "busy",
        title: "When busy",
        instructions: ["Forward only calls that meet a busy line."],
        dial_code: "*67*0187654321#",
        disable_code: "##67#",
        source_url: "https://assistance.orange.fr/conditional-forwarding",
      },
      {
        condition: "unreachable",
        title: "When unreachable",
        instructions: ["Forward only when the line cannot be reached."],
        dial_code: null,
        disable_code: null,
        source_url: null,
      },
    ],
  };
}

export function activationSnapshot(overrides: Partial<ActivationSnapshot> = {}): ActivationSnapshot {
  return {
    workflow_version: 1,
    stage: "forwarding_required",
    completed_milestones: ["profile_confirmed", "payment_eligible", "provisioning_consented", "number_provisioned"],
    next_action: "configure_forwarding",
    blockers: ["forwarding_not_verified"],
    warnings: [],
    profile: {
      owner_name: "Maya",
      business_name: "Atelier Maya",
      business_type: "Florist",
      public_description: "A neighbourhood flower studio.",
      timezone: "Europe/Paris",
      business_hours: null,
      existing_phone_e164: "+33612345678",
      confirmed_carrier: "orange",
      receptionist_name: "Camille",
      faqs: [],
      special_instructions: null,
      escalation_notes: null,
      detected_carrier: "orange",
      detected_number_type: "fixed",
      carrier_lookup_status: "succeeded",
      carrier_looked_up_at: "2026-07-17T09:00:00Z",
      content_revision: 1,
      routing_revision: 1,
    },
    profile_constraints: {
      name_max_length: 100,
      business_type_max_length: 100,
      public_description_max_length: 1_000,
      faq_max_items: 20,
      faq_question_max_length: 200,
      faq_answer_max_length: 1_000,
      special_instructions_max_length: 2_000,
      escalation_notes_max_length: 2_000,
      max_intervals_per_day: 2,
      phone_country: "FR",
    },
    activation: {
      profile_confirmed_at: "2026-07-17T08:00:00Z",
      provisioning_consented_at: "2026-07-17T08:10:00Z",
      verification_window_started_at: null,
      verification_window_expires_at: null,
      verification_status: "not_started",
      forwarding_verified_at: null,
      go_live_approved_at: null,
      activated_at: null,
      last_failure_code: null,
    },
    billing: {
      eligible: true,
      plan_tier: "starter",
      subscription_status: "active",
      allocated_minutes: 60,
      minutes_remaining: 60,
      current_period_start: "2026-07-17T08:00:00Z",
      current_period_end: "2026-08-16T08:00:00Z",
    },
    number: {
      assigned_e164: "+33187654321",
      country_code: "FR",
      provider_ready: true,
      provisioning_status: "succeeded",
      can_retry: false,
    },
    forwarding: forwardingGuide(),
    runtime_readiness: {
      stage: "ready",
      can_provision_number: true,
      can_activate: false,
      should_enable_phone: false,
      can_route: false,
      blockers: ["forwarding_not_verified", "agent_disabled", "phone_inactive", "go_live_not_approved"],
      warnings: [],
      policy_version: "runtime-v3",
    },
    evaluated_at: "2026-07-17T10:00:00Z",
    ...overrides,
  };
}
