"""Public API for Presvo's versioned wire contracts."""

from .dispatch import (
    AGENT_NAME_MAX_LENGTH,
    KNOWLEDGE_BASE_MAX_LENGTH,
    OWNER_CONTEXT_MAX_LENGTH,
    OWNER_NAME_MAX_LENGTH,
    SYSTEM_PROMPT_MAX_LENGTH,
    VERIFICATION_MESSAGE,
    AgentName,
    CustomerCallDispatch,
    DispatchContract,
    ForwardingVerificationDispatch,
    KnowledgeBase,
    OwnerContext,
    OwnerName,
    SystemPrompt,
    parse_dispatch,
)
from .completion import (
    CallCompletionAcknowledgement,
    CallCompletionRequest,
    VerificationCompletionAcknowledgement,
    VerificationCompletionRequest,
)
from .transcript import (
    TRANSCRIPT_TEXT_MAX_LENGTH,
    TranscriptAppendAcknowledgement,
    TranscriptAppendRequest,
    TranscriptSegment,
    TranscriptSequenceNumber,
    TranscriptSpeaker,
    TranscriptText,
)
from .versioning import (
    CURRENT_SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    ContractError,
    VersionedContract,
    create_contract,
    dump_contract,
    dump_contract_json,
    parse_contract,
)

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "SUPPORTED_SCHEMA_VERSIONS",
    "AGENT_NAME_MAX_LENGTH",
    "OWNER_NAME_MAX_LENGTH",
    "OWNER_CONTEXT_MAX_LENGTH",
    "SYSTEM_PROMPT_MAX_LENGTH",
    "KNOWLEDGE_BASE_MAX_LENGTH",
    "VERIFICATION_MESSAGE",
    "TRANSCRIPT_TEXT_MAX_LENGTH",
    "AgentName",
    "OwnerName",
    "OwnerContext",
    "SystemPrompt",
    "KnowledgeBase",
    "TranscriptSequenceNumber",
    "TranscriptText",
    "ContractError",
    "VersionedContract",
    "CustomerCallDispatch",
    "ForwardingVerificationDispatch",
    "TranscriptSpeaker",
    "TranscriptSegment",
    "TranscriptAppendRequest",
    "TranscriptAppendAcknowledgement",
    "CallCompletionRequest",
    "CallCompletionAcknowledgement",
    "VerificationCompletionRequest",
    "VerificationCompletionAcknowledgement",
    "DispatchContract",
    "create_contract",
    "parse_contract",
    "dump_contract",
    "dump_contract_json",
    "parse_dispatch",
]
